"""empty message

Revision ID: 89e96d2af81b
Revises: 005ddc67f0d6
Create Date: 2020-12-05 13:55:10.688403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e96d2af81b'
down_revision = '005ddc67f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fornecedor', 'data_nascimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedor', sa.Column('data_nascimento', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
