"""create tables e relations tipo_servico

Revision ID: 0ad953cf53e9
Revises: 8eb86e7d6bba
Create Date: 2020-09-05 16:53:53.551445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad953cf53e9'
down_revision = '8eb86e7d6bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacao', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamento_tipo_servico',
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], )
    )
    op.create_table('produto_tipo_servico',
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_tipo_servico')
    op.drop_table('equipamento_tipo_servico')
    op.drop_table('tipo_servico')
    # ### end Alembic commands ###
