"""create table equipamento

Revision ID: 4ef6de4cee3b
Revises: f074a1f559c9
Create Date: 2020-09-05 16:00:47.050222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef6de4cee3b'
down_revision = 'f074a1f559c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('preco_tempo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacao', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamento')
    # ### end Alembic commands ###
