"""create table equipamento_compra

Revision ID: 8eb86e7d6bba
Revises: 4ef6de4cee3b
Create Date: 2020-09-05 16:08:05.891787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb86e7d6bba'
down_revision = '4ef6de4cee3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamento_compra',
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamento_compra')
    # ### end Alembic commands ###
