"""create table tipo_quantidade

Revision ID: c168ea321795
Revises: d0d35bf25b7e
Create Date: 2020-09-05 15:13:40.548899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c168ea321795'
down_revision = 'd0d35bf25b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo__quantidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.Column('sigla', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo__quantidade')
    # ### end Alembic commands ###
