"""create table produto

Revision ID: e560a7e3a1e4
Revises: c168ea321795
Create Date: 2020-09-05 15:31:03.539016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e560a7e3a1e4'
down_revision = 'c168ea321795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_quantidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.Column('sigla', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('tipo_quantidade_id', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacao', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['tipo_quantidade_id'], ['tipo_quantidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tipo__quantidade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo__quantidade',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('sigla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('produto')
    op.drop_table('tipo_quantidade')
    # ### end Alembic commands ###
