"""alter table produto

Revision ID: f074a1f559c9
Revises: c8f12e999db7
Create Date: 2020-09-05 15:59:03.440114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f074a1f559c9'
down_revision = 'c8f12e999db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('preco_un', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('produto', 'preco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('preco', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('produto', 'preco_un')
    # ### end Alembic commands ###
